language: node_js
node_js: stable

cache:
  directories:
    - node_modules
before_install:
  # - npm install hexo-cli -g

install:
  - npm install
  # - npm install hexo-deployer-git --save

script:
  # - hexo clean
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "ynwshy"
  - git config user.email "ynwshy@126.com"
  - git add .
  - git commit -m "Update docs"
  # - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://${github_personal_access_token}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/ynwshy/ynwshy.github.io.git